version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Harilatha@515
      MYSQL_DATABASE: erp_project
    networks:
      - springboot-mysql

  app:
    build: .
    container_name: erp_app
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/erp_project
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Harilatha@515
    networks:
      - springboot-mysql

networks:
  springboot-mysql:
    driver: bridge
